---
title: "CPLN675_midterm"
author: "Jenna Epstein and Kristin Chang"
date: "March 31, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(caret)
library(pscl)
library(plotROC)
library(pROC)
library(sf)
library(tidyverse)
library(knitr)
library(kableExtra)
library(FNN)


mapTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle=element_text(face="italic"),
    plot.caption=element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),axis.title = element_blank(),
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2)
  )
}

```

```{r, load fishnet for calgary}
# CALGARY: Load Calgary fishnet generated in ArcGIS Pro (200x200m cells).
calgary_fishnet <- st_read("Data_Calgary/Calgary_new/for_R/calgary_fishnet.shp") %>%
st_as_sf() %>% st_transform('EPSG:3780')

calgary_fishnet$ID_fishnet <-as.character(calgary_fishnet$ID_fishnet)

```


```{r, load boundary for calgary}
calgary_boundary <- st_read("provided_midTermProject_Data/CALGIS_CITYBOUND_LIMIT/CALGIS_CITYBOUND_LIMIT.shp")

ggplot() +
  geom_sf(data=calgary_boundary, fill="grey") +
  geom_sf(data=calgary_fishnet, alpha=0.2) + mapTheme()

```

```{r, load inundatation for calgary}
# CALGARY: Inundation classification (generated by reclassifying the initial inundation raster, and calculated using zonal statistics (maximum)).
calgary_inundation <- st_read("Data_Calgary/Calgary_new/for_R/cal_inun_max.xls") %>%
  dplyr::select(OID, MAX) %>%
  dplyr::rename(ID_fishnet = OID) %>%
  dplyr::rename(inundation = MAX)


calgary_inundation$ID_fishnet <-as.character(calgary_inundation$ID_fishnet)

calgary_inundation_grid <- left_join(calgary_inundation, calgary_fishnet) %>% st_as_sf()
calgary_fishnet_new <-  calgary_inundation_grid

```


```{r, load elevation mean for calgary}
# CALGARY: Elevation mean (calculated using zonal statistics (mean)).
calgary_elev <- st_read("Data_Calgary/Calgary_new/for_R/cal_elev_mean.xls") %>%
  dplyr::select(OID, MEAN) %>%
  dplyr::rename(ID_fishnet = OID) %>%
  dplyr::rename(elevation_mean = MEAN)

calgary_elev$ID_fishnet <-as.character(calgary_elev$ID_fishnet)

calgary_elev_grid <- full_join(calgary_elev, calgary_fishnet_new) %>% st_as_sf()
calgary_fishnet_new <- calgary_elev_grid


```

```{r, prep streams for calgary}
# CALGARY: Stream network, generated using the ArcHydro workflow from the week4 lab in ArcGIS Pro.
calgary_streams <- st_read("HydroData_Calgary_ArcGIS/Data/cal_stream.shp") %>%
  dplyr::rename(ID_stream = arcid) 

```

```{r, visualize streams for fun}
ggplot() +
  geom_sf(data=calgary_boundary, fill="grey") +
  #geom_sf(data=calgary_fishnet, alpha=0.2) + 
  geom_sf(data=calgary_streams, color="blue") +mapTheme()
```

```{r, load the near_dist table from arcgis for streams}
calgary_streams_neardist <- st_read("HydroData_Calgary_ArcGIS/Data/cal_stream_neardist.xls")  %>%
  dplyr::select(-Rowid, -OBJECTID, -NEAR_FID) %>%
  dplyr::rename(ID_fishnet = IN_FID)

##FYI was having trouble calculating distance to line using dist2Line in geosphere package in R, so decided to use the generate near table in ArcGIS to calculate from fishnet to stream. I have no idea if it used the centroid, though.

calgary_streams_neardist$ID_fishnet <-as.character(calgary_streams_neardist$ID_fishnet)

calgary_streamneardist_grid <- full_join(calgary_streams_neardist, calgary_fishnet_new) %>% st_as_sf()
calgary_fishnet_new <-  calgary_streamneardist_grid

```

```{r, prep flow accumulation for calgary}
# CALGARY: flow accumulation mean per fishnet cell. Generated using zonal statistics (mean).
calgary_flowacc <- st_read("HydroData_Calgary_ArcGIS/Data/cal_flowacc_mean.xls") %>%
  dplyr::rename(ID_fishnet = ID_FISHNET) %>%
  dplyr::rename(flowacc_mean = MEAN) %>%
  dplyr::select(-Rowid, -COUNT, -AREA, -ZONE.CODE)

calgary_flowacc$ID_fishnet <-as.character(calgary_flowacc$ID_fishnet)

calgary_flowacc_grid <- full_join(calgary_flowacc, calgary_fishnet_new) %>%st_as_sf()
calgary_fishnet_new <- calgary_flowacc_grid 

```

```{r, load and prep slope for calgary}
# CALGARY: Slope mean per fishnet cell. Generated using zonal statistics (mean).
calgary_slope <- st_read("HydroData_Calgary_ArcGIS/Data/cal_slope_mean.xls") %>%
  dplyr::rename(ID_fishnet = ID_FISHNET) %>%
  dplyr::rename(slope_mean = MEAN) %>%
  dplyr::select(-Rowid, -COUNT, -AREA, -ZONE.CODE)

calgary_slope$ID_fishnet <-as.character(calgary_slope$ID_fishnet)

calgary_slope_grid <- full_join(calgary_slope, calgary_fishnet_new) %>% st_as_sf()
calgary_fishnet_new <- calgary_slope_grid

```

```{r, calculate impervious surface area for calgary per cell}
# CALGARY: Impervious surface area (calculate per fishnet cell in R and prep to join to fishnet later). FYI THIS IS A MASSIVE FILE AND GITHUB IS YELLING AT ME AND CAN'T LOAD IT, SO I ZIPPED IT UP AND YOU'LL NEED TO SAVE IT LOCALLY
calgary_landCover <- st_read("Data_Calgary/LandCover/geo_export_b68ee7b7-76c0-4bf4-96d2-02b12a13fe5f.shp")

# Reclassify land classes, impervious vs impervious. Just keep impervious.
calgary_landCover <- calgary_landCover %>% 
  mutate(impervious = case_when(lc_cat %in% c("Building/Paved", "Construction",
                                        "PavedTrails") ~ "Impervious",
                                lc_cat %in% c("Roads/Raillines", "SportFacility") ~ "Impervious",
                            TRUE ~ "Non-Impervious")) %>% 
                      filter(impervious == "Impervious")
# Reproject
calgary_landCover <- calgary_landCover %>% 
  select(lc_cat, impervious) %>% 
  st_transform(crs = st_crs(calgary_fishnet_new))

# st_area
calgary_landCover <- calgary_landCover %>% 
  mutate(impervious_area = st_area(calgary_landCover))
```



```{r}
imperv_grid <- st_join(calgary_fishnet_new, calgary_landCover)


imperv_grid <- imperv_grid %>% 
  data.frame(.) %>% 
  group_by(ID_fishnet) %>% 
  summarise(impervious_area = sum(impervious_area, na.rm = TRUE))

calgary_fishnet_new <- calgary_fishnet_new %>% 
  inner_join(imperv_grid)


```
## something happened with inundation reclassification, will need to redo it in arcgis pro. for now, I'll reclassify here

```{r}
calgary_fishnet_new <- calgary_fishnet_new %>%
  mutate(inundation_reclass=ifelse(str_detect(calgary_fishnet_new$inundation, "2"), "yes", "no"))
```

###


```{r}
calgary_boundary <- calgary_boundary %>% st_transform('EPSG:3780')

```

```{r}
# Centroid-in-polygon join to see which cells have their centroid in the buffer
selectCentroids <-
  st_centroid(calgary_fishnet_new)[calgary_boundary,] %>%
  st_drop_geometry() %>%
  left_join(dplyr::select(calgary_fishnet_new, ID_fishnet)) %>%
  st_sf()

calgary_fishnet_final <- selectCentroids 
```

```{r}
ggplot() + 
  geom_sf(data=calgary_fishnet_final, aes(fill=as.factor(inundation_reclass))) +
  scale_fill_manual(values = c("navy", "darkgreen"),
                    labels = c("yes","no"),
                    name = "") +
  labs(title="Inundation in Calgary, by way of the fishnet") +
  geom_sf(data=calgary_boundary, color="black", fill=NA)+
  mapTheme()

```

